// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyIBibwe2Ucfv-nNC_yNVOR3s7gL4JQ_o',
    appId: '1:50656425516:web:13264598b581c8d3f64389',
    messagingSenderId: '50656425516',
    projectId: 'product-triprizeweb-dev',
    authDomain: 'product-triprizeweb-dev.firebaseapp.com',
    storageBucket: 'product-triprizeweb-dev.firebasestorage.app',
    measurementId: 'G-BSVWDW1FHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcEB-E2363X8ZHDVEDXLW0jtPUk1eddok',
    appId: '1:50656425516:android:9932e548d8c36379f64389',
    messagingSenderId: '50656425516',
    projectId: 'product-triprizeweb-dev',
    storageBucket: 'product-triprizeweb-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36KyzHc58dBucD2X8PMrytEW9FgyB1mk',
    appId: '1:50656425516:ios:3f5a311fe3f9d0e3f64389',
    messagingSenderId: '50656425516',
    projectId: 'product-triprizeweb-dev',
    storageBucket: 'product-triprizeweb-dev.firebasestorage.app',
    iosBundleId: 'com.triprizeshuang.triprizeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyIBibwe2Ucfv-nNC_yNVOR3s7gL4JQ_o',
    appId: '1:50656425516:web:13264598b581c8d3f64389',
    messagingSenderId: '123456789',
    projectId: 'product-triprizeweb-dev',
    storageBucket: 'product-triprizeweb-dev.firebasestorage.app',
    iosBundleId: 'product-triprizeweb-dev.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyIBibwe2Ucfv-nNC_yNVOR3s7gL4JQ_o',
    appId: '1:50656425516:web:b9bd9239423b20e6f64389',
    messagingSenderId: '50656425516',
    projectId: 'product-triprizeweb-dev',
    authDomain: 'product-triprizeweb-dev.firebaseapp.com',
    storageBucket: 'product-triprizeweb-dev.firebasestorage.app',
    measurementId: 'G-LH82XWP5R7',
  );

}