// Mocks generated by Mockito 5.4.4 from annotations
// in triprize_mobile/test/features/purchase/presentation/providers/purchase_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:triprize_mobile/features/purchase/data/models/purchase_model.dart'
    as _i2;
import 'package:triprize_mobile/features/purchase/domain/repositories/purchase_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePurchaseModel_0 extends _i1.SmartFake implements _i2.PurchaseModel {
  _FakePurchaseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PurchaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseRepository extends _i1.Mock
    implements _i3.PurchaseRepository {
  MockPurchaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PurchaseModel> createPurchase(
          _i2.CreatePurchaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPurchase,
          [request],
        ),
        returnValue: _i4.Future<_i2.PurchaseModel>.value(_FakePurchaseModel_0(
          this,
          Invocation.method(
            #createPurchase,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.PurchaseModel>);

  @override
  _i4.Future<List<_i2.PurchaseModel>> getPurchaseHistory({
    String? campaignId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPurchaseHistory,
          [],
          {
            #campaignId: campaignId,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.PurchaseModel>>.value(<_i2.PurchaseModel>[]),
      ) as _i4.Future<List<_i2.PurchaseModel>>);

  @override
  _i4.Future<_i2.PurchaseModel> getPurchaseById(String? purchaseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPurchaseById,
          [purchaseId],
        ),
        returnValue: _i4.Future<_i2.PurchaseModel>.value(_FakePurchaseModel_0(
          this,
          Invocation.method(
            #getPurchaseById,
            [purchaseId],
          ),
        )),
      ) as _i4.Future<_i2.PurchaseModel>);

  @override
  _i4.Future<_i2.PurchaseModel> confirmPayment(String? purchaseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPayment,
          [purchaseId],
        ),
        returnValue: _i4.Future<_i2.PurchaseModel>.value(_FakePurchaseModel_0(
          this,
          Invocation.method(
            #confirmPayment,
            [purchaseId],
          ),
        )),
      ) as _i4.Future<_i2.PurchaseModel>);

  @override
  _i4.Future<void> cancelPurchase(String? purchaseId) => (super.noSuchMethod(
        Invocation.method(
          #cancelPurchase,
          [purchaseId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
