package jp.co.softroad.liteflow;

import com.yomahub.liteflow.core.FlowExecutor;
import com.yomahub.liteflow.enums.NodeTypeEnum;
import com.yomahub.liteflow.flow.LiteflowResponse;
import com.yomahub.liteflow.publisher.PublishChainRequest;
import com.yomahub.liteflow.publisher.PublishResult;
import com.yomahub.liteflow.publisher.PublishScriptRequest;
import com.yomahub.liteflow.publisher.RulePublisher;
import com.yomahub.liteflow.publisher.RulePublisherFactory;
import com.yomahub.liteflow.repository.RuleDbSyncManager;
import com.yomahub.liteflow.repository.sql.SqlPublisherConfig;
import jp.co.softroad.liteflow.model.MigrationContext;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * 本PoCの主張そのものを守るテスト。すなわち変換出力はコードではなく設定によって決まる、
 * という主張である。検査する手段は2つ。テンプレート表（リクエストデータ）と、
 * Rule-DB に格納したスクリプトノードのソースであり、いずれの実行でも再起動も再ビルドも行わない。
 *
 * <p>検査しないこと: COBOL構文解析の網羅性、およびCOBOL入力と生成Javaの意味的等価性。
 */
@SpringBootTest
class RuleDrivenTransformTest {
    private static final String H2_URL = "jdbc:h2:mem:ruledb;DB_CLOSE_DELAY=-1;MODE=MySQL";

    private static final List<String> SOURCE = List.of(
            "MOVE WS-CUSTOMER-NAME TO WS-OUT-NAME.",
            "ADD 1 TO WS-RECORD-COUNT.",
            "PERFORM SOME-UNSUPPORTED-PARA.");

    @Autowired
    private FlowExecutor flowExecutor;

    @Test
    void templatesAndDbScriptsDriveTheGeneratedCode() {
        String suffix = UUID.randomUUID().toString().replace("-", "").substring(0, 12);
        String chainId = "itTransform" + suffix;
        String scriptNodeId = "itPostProcess" + suffix;

        try (RulePublisher publisher = RulePublisherFactory.create(SqlPublisherConfig.builder()
                .applicationName("liteflow-validation-platform-test")
                .url(H2_URL)
                .username("sa")
                .password("")
                .build())) {

            publisher.publishChain(PublishChainRequest.builder()
                    .chainId(chainId)
                    .el("THEN(validate,transform,report)")
                    .expectedVersion(0L)
                    .build());
            RuleDbSyncManager.reconcileOnce();

            // 手段1: 同じchain、同じjar。違うのはテンプレート表だけ。
            String withTemplatesV1 = run(chainId, templates("${target} = ${source};", "// TODO: ${line}"));
            String withTemplatesV2 = run(chainId, templates("this.${target} = this.${source};", "// REVIEW: ${line}"));

            Assertions.assertTrue(withTemplatesV1.contains("WS-OUT-NAME = WS-CUSTOMER-NAME;"),
                    "template v1 output was: " + withTemplatesV1);
            Assertions.assertTrue(withTemplatesV2.contains("this.WS-OUT-NAME = this.WS-CUSTOMER-NAME;"),
                    "template v2 output was: " + withTemplatesV2);
            Assertions.assertNotEquals(withTemplatesV1, withTemplatesV2,
                    "swapping the template table must change the generated code");

            // 手段2: 変換ロジックそのものを Rule-DB に格納する。
            PublishResult scriptV1 = publisher.publishScript(PublishScriptRequest.builder()
                    .nodeId(scriptNodeId)
                    .script("migrationContext.emit(\"// generated by script v1\");")
                    .name("post process")
                    .type(NodeTypeEnum.SCRIPT)
                    .language("groovy")
                    .expectedVersion(0L)
                    .build());
            Assertions.assertEquals(1L, scriptV1.getVersion());

            publisher.publishChain(PublishChainRequest.builder()
                    .chainId(chainId)
                    .el("THEN(validate,transform," + scriptNodeId + ",report)")
                    .expectedVersion(1L)
                    .build());
            RuleDbSyncManager.reconcileOnce();

            String withScriptV1 = run(chainId, templates("${target} = ${source};", "// TODO: ${line}"));
            Assertions.assertTrue(withScriptV1.contains("// generated by script v1"),
                    "script v1 output was: " + withScriptV1);

            // 変わるのはスクリプト本文だけ。chain もjarもプロセスもそのまま。
            PublishResult scriptV2 = publisher.publishScript(PublishScriptRequest.builder()
                    .nodeId(scriptNodeId)
                    .script("migrationContext.emit(\"// generated by script v2\");")
                    .name("post process")
                    .type(NodeTypeEnum.SCRIPT)
                    .language("groovy")
                    .expectedVersion(scriptV1.getVersion())
                    .build());
            Assertions.assertEquals(2L, scriptV2.getVersion());
            RuleDbSyncManager.reconcileOnce();

            String withScriptV2 = run(chainId, templates("${target} = ${source};", "// TODO: ${line}"));
            Assertions.assertTrue(withScriptV2.contains("// generated by script v2"),
                    "script v2 output was: " + withScriptV2);
            Assertions.assertNotEquals(withScriptV1, withScriptV2,
                    "editing only the Rule-DB script must change the generated code");
        }
    }

    private String run(String chainId, Map<String, String> templates) {
        MigrationContext context = new MigrationContext("transform-test");
        context.setSourceLines(SOURCE);
        context.setTemplates(templates);
        LiteflowResponse response = flowExecutor.execute2Resp(chainId, "transform-test", context);
        Assertions.assertTrue(response.isSuccess(),
                () -> "chain failed: " + (response.getCause() == null ? "?" : response.getCause().toString()));
        return context.getGeneratedCode();
    }

    private static Map<String, String> templates(String move, String unknown) {
        Map<String, String> map = new LinkedHashMap<>();
        map.put("move", move);
        map.put("add", "${target} += ${source};");
        map.put("display", "System.out.println(${value});");
        map.put("unknown", unknown);
        return map;
    }
}
