global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: liteflow-executors
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - executor-a:8080
          - executor-b:8080
